[common]
# ログディレクトリ
log_dir = "logs"
# ログファイルエンコード
encode = "utf-8"

# タイムゾーン (JST)
tz_offset_hours = 9


[devices]
# Logger (gm10)
gm10_visa = "TCPIP0::192.168.1.105::34434::SOCKET"
# Heater Power Supply (pfr_100l50)
hps_visa = "TCPIP0::192.168.1.111::2268::SOCKET"
# AMD Power Supply (pfr_100l50)
aps_visa = "TCPIP0::192.168.1.112::2268::SOCKET"

# デバイスマネージャーでのCOMポート番号 (例: COM3) (-1以下 → 無効化)
# PWUX (Temp)
pwux_com_port = -1
# Laser (ibeam)
ibeam_com_port = -1

[devices.gm10]
ext_ch = 1 # 真空度測定Ch番号
sip_ch = 2 # SIP測定Ch番号
pc_ch = 10 # フォトカレント測定Ch番号
hv_ch = 22 # HV制御出力Ch番号
tc_ch = -1 # TC測定Ch番号

[devices.hps] # Heater power supply
unit = 0
v_limit = 18 # 最大印加電圧[V]
ovp = 19     # 過電圧保護値[V]
ocp = 10     # 過電流保護値[A]

[devices.amd]
unit = 0
v_limit = 18 # 最大印加電圧[V]
ovp = 19     # 過電圧保護値[V]
ocp = 5      # 過電流保護値[A]

[devices.ibeam]
beam_ch = 2
