[colors]
Cs = "red"
O2 = "blue"
"Cs(3.0A)" = "orange"
"Cs(3.8A)" = "chocolate"
Event = "green"
LaserEngChange = "green"

[plots."250904_2.1"]
spans = [
    { event = "Cs", start = 97.1, end = 735.7, label = "Cs (3.5A)" },
    { event = "O2", start = 735.7, end = 745.7 },
    { event = "Cs", start = 880.3, end = 1374.6 },
    { event = "O2", start = 1419.8, end = 1491.1, label = "$\\mathrm{O_2}$" },
    { event = "Cs", start = 1607.6, end = 1758.6 },
    { event = "O2", start = 1816.8, end = 1862.2 },
    { event = "Cs", start = 1954.4, end = 2385.9 },
    { event = "O2", start = 2539.8, end = 2645.6 },
    { event = "Cs", start = 2693.0, end = 2829.1 },
]

[plots."251015_2.2"]
spans = [
    { event = "Cs", start = 217.3, end = 3108.6, label = "Cs (3.5A)" },
    { event = "O2", start = 3272.6, end = 3477.6, label = "$\\mathrm{O_2}$" },
    { event = "Cs", start = 3652.4, end = 4034.4 },
    { event = "Cs(3.0A)", start = 4034.4, end = 4494.1, label = "Cs (3.0A)" },
]
points = [
    { event = "LaserEngChange", time = 1191.4, label = "Laser \n 3mW â†’ 6mW â†’ 25mW", y = 0.7 },
]

[plots."251015_3.3"]
spans = [
    { event = "Cs", start = 146.9, end = 2410.6, label = "Cs (3.5A)" },
    { event = "O2", start = 2792.8, end = 2998.3, label = "$\\mathrm{O_2}$" },
    { event = "Cs", start = 3064.3, end = 3064.3 },
    { event = "Cs(3.8A)", start = 3064.3, end = 4094.8, label = "Cs (3.8A)" },
    { event = "O2", start = 4188.8, end = 4270.9 },
    { event = "Cs(3.8A)", start = 4333.2, end = 4636.3 },
]
