[250904."[2.1]NEA-20250917101546"]
event_spans = [
    { event_name = "Cs", start_sec = 97.1, end_sec = 735.7, label = "Cs (3.5A)" },
    { event_name = "O2", start_sec = 735.7, end_sec = 745.7 },
    #
    { event_name = "Cs", start_sec = 880.3, end_sec = 1374.6 },
    { event_name = "O2", start_sec = 1419.8, end_sec = 1491.1, label = "$\\mathrm{O_2}$" },
    #
    { event_name = "Cs", start_sec = 1607.6, end_sec = 1758.6 },
    { event_name = "O2", start_sec = 1816.8, end_sec = 1862.2 },
    #
    { event_name = "Cs", start_sec = 1954.4, end_sec = 2385.9 },
    { event_name = "O2", start_sec = 2539.8, end_sec = 2645.6 },
    #
    { event_name = "Cs", start_sec = 2693.0, end_sec = 2829.1 },
]

[251015."[2.2]NEA-20251028153023"]
event_spans = [
    { event_name = "Cs", start_sec = 217.3, end_sec = 3108.6, label = "Cs (3.5A)", label_dx_sec = 200.0 },
    { event_name = "O2", start_sec = 3272.6, end_sec = 3477.6, label = "$\\mathrm{O_2}$" },
    #
    { event_name = "Cs", start_sec = 3652.4, end_sec = 4034.4 },
    { event_name = "Cs(3.0A)", start_sec = 4034.4, end_sec = 4494.1, label = "Cs (3.0A)", label_dx_sec = 200.0 },
    #
    { event_name = "LaserEngChange", start_sec = 1191.4, end_sec = 1415.9, label = "Laser \n 3mW → 6mW → 25mW", label_y = 0.7 },
]

[251015."[3.3]NEA-20251104140916"]
event_spans = [
    { event_name = "Cs", start_sec = 146.9, end_sec = 2410.6, label = "Cs (3.5A)" },
    { event_name = "O2", start_sec = 2792.8, end_sec = 2998.3, label = "$\\mathrm{O_2}$" },
    #
    { event_name = "Cs", start_sec = 3064.3, end_sec = 3064.3 },
    { event_name = "Cs(3.8A)", start_sec = 3064.3, end_sec = 4094.8, label = "Cs (3.8A)", label_dx_sec = 200.0, label_y = 0.98 },
    { event_name = "O2", start_sec = 4188.8, end_sec = 4270.9 },
    #
    { event_name = "Cs(3.8A)", start_sec = 4333.2, end_sec = 4636.3 },
]
